#!/bin/sh
# Concatenate every script file into one, for a two-file install.
# Regenerate after changing any .gs file.
set -e
cd "$(dirname "$0")"

ORDER="lexicon phrases verbForms tokenize phraseMatch passiveRule \
nominalizationRule lightVerbRule phraseRule authorityRule agreementRule \
referenceRule inflatedRule rules Code"

mkdir -p bundle
{
  echo "// Passive Voice Lens - generated by build.sh, do not edit directly."
  echo "// Edit the individual .gs files and re-run ./build.sh instead."
  for name in $ORDER; do
    echo ""
    echo "// ===== $name.gs ====="
    cat "$name.gs"
  done
} > bundle/PassiveVoiceLens.gs

cp Sidebar.html bundle/Sidebar.html
cp WebApp.html bundle/WebApp.html
echo "bundle/PassiveVoiceLens.gs written ($(wc -l < bundle/PassiveVoiceLens.gs) lines)"
