// Passive Voice Lens - generated by build.sh, do not edit directly.
// Edit the individual .gs files and re-run ./build.sh instead.

// ===== lexicon.gs =====
/**
 * Word lists backing passive-voice detection.
 * Data only -- no logic. Plain globals for Apps Script compatibility.
 */

const BE_FORMS = Object.freeze([
  'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', "isn't", "aren't",
  "wasn't", "weren't", "ain't"
])

const GET_FORMS = Object.freeze(['get', 'gets', 'got', 'gotten', 'getting'])

/** Adverbs and negators allowed between the be-verb and the participle. */
const INTERVENERS = Object.freeze([
  'not', 'never', 'also', 'already', 'only', 'just', 'still', 'then', 'thus',
  'therefore', 'however', 'again', 'now', 'always', 'sometimes', 'rarely',
  'seldom', 'often', 'usually', 'generally', 'typically', 'widely', 'largely',
  'recently', 'previously', 'subsequently', 'currently', 'clearly', 'simply',
  'further', 'well', 'both', 'all', 'therefore', 'consequently', 'indeed',
  'nevertheless', 'increasingly', 'consistently', 'explicitly', 'implicitly'
])

/** Irregular past participles that do not end in -ed. */
const IRREGULAR_PARTICIPLES = Object.freeze([
  'arisen', 'awoken', 'beaten', 'become', 'begun', 'bent', 'bet', 'bitten',
  'bled', 'blown', 'born', 'borne', 'bought', 'bound', 'bred', 'broadcast',
  'broken', 'brought', 'built', 'burnt', 'burst', 'cast', 'caught', 'chosen',
  'clung', 'come', 'cost', 'cut', 'dealt', 'done', 'drawn', 'driven', 'drunk',
  'eaten', 'fallen', 'fed', 'felt', 'fought', 'found', 'flown', 'forbidden',
  'forgotten', 'forgiven', 'forsaken', 'frozen', 'given', 'gone', 'ground',
  'grown', 'heard', 'held', 'hidden', 'hit', 'hung', 'hurt', 'kept', 'known',
  'laid', 'led', 'left', 'lent', 'let', 'lost', 'made', 'meant', 'met',
  'mistaken', 'overcome', 'overtaken', 'paid', 'proven', 'put', 'read',
  'rebuilt', 'redone', 'rewritten', 'ridden', 'risen', 'run', 'said', 'seen',
  'sent', 'set', 'sewn', 'shaken', 'shed', 'shone', 'shot', 'shown', 'shrunk',
  'shut', 'slain', 'slept', 'slid', 'sold', 'sought', 'sown', 'spent', 'spilt',
  'split', 'spoken', 'spread', 'sprung', 'stolen', 'stood', 'stricken',
  'struck', 'strung', 'stuck', 'sung', 'sunk', 'swept', 'swollen', 'swum',
  'swung', 'taken', 'taught', 'thought', 'thrown', 'told', 'torn', 'trodden',
  'undergone', 'understood', 'undertaken', 'undone', 'upheld', 'upset',
  'withdrawn', 'withheld', 'withstood', 'won', 'worn', 'woven', 'written',
  'wrung'
])

/**
 * -ed words that read as adjectives after a be-verb far more often than as
 * true passives. Suppressing these is the single biggest false-positive win.
 */
const ADJECTIVAL_ED = Object.freeze([
  'aged', 'advanced', 'alleged', 'ashamed', 'based', 'bored', 'closed',
  'committed', 'complicated', 'concerned', 'confused', 'crowded', 'dedicated',
  'delighted', 'detailed', 'disappointed', 'distinguished', 'divided',
  'embarrassed', 'excited', 'experienced', 'frustrated', 'gifted',
  'interested', 'involved', 'limited', 'located', 'married', 'mixed',
  'motivated', 'pleased', 'prepared', 'qualified', 'related', 'retired',
  'satisfied', 'scared', 'situated', 'skilled', 'supposed', 'surprised',
  'talented', 'tired', 'united', 'unlimited', 'unexpected', 'worried'
])

/** Words ending in -ed that are not participles at all. */
const NON_PARTICIPLE_ED = Object.freeze([
  'indeed', 'hundred', 'sacred', 'wicked', 'naked', 'wretched', 'need',
  'feed', 'breed', 'speed', 'deed', 'seed', 'greed', 'creed', 'weed',
  'bleed', 'heed', 'exceed', 'proceed', 'succeed', 'embed'
])

const DETERMINERS = Object.freeze([
  'the', 'a', 'an', 'this', 'that', 'these', 'those', 'its', 'their',
  'our', 'his', 'her', 'my', 'your', 'such'
])

/** Suffixes that usually mark a verb turned into an abstract noun. */
const NOMINALIZATION_SUFFIXES = Object.freeze([
  'tion', 'sion', 'ment', 'ance', 'ence', 'ity', 'ness', 'ism'
])

/** Nominalizations the suffix test misses. */
const NOMINALIZATION_EXTRAS = Object.freeze([
  'use', 'usage', 'analysis', 'emphasis', 'failure', 'pressure', 'growth',
  'procedure', 'disclosure', 'exposure', 'coverage', 'storage', 'leverage',
  'uptake', 'intake', 'spread', 'reliance', 'oversight'
])

/** Concrete nouns that happen to end in a nominalizing suffix. */
const NOMINALIZATION_STOPLIST = Object.freeze([
  'university', 'community', 'opportunity', 'security', 'majority', 'minority',
  'variety', 'society', 'city', 'entity', 'identity', 'quantity', 'quality',
  'moment', 'element', 'document', 'instrument', 'government', 'department',
  'environment', 'experiment', 'equipment', 'component', 'parliament',
  'distance', 'instance', 'audience', 'science', 'evidence', 'experience',
  'business', 'witness', 'illness', 'wilderness', 'nation', 'station',
  'question', 'section', 'portion', 'fraction', 'version', 'mission'
])

/** Irregular past-tense forms, used to stop a noun phrase at the verb. */
const IRREGULAR_PAST = Object.freeze([
  'took', 'made', 'gave', 'found', 'led', 'came', 'went', 'saw', 'became',
  'said', 'held', 'kept', 'left', 'sent', 'brought', 'thought', 'began',
  'grew', 'drew', 'fell', 'felt', 'met', 'ran', 'rose', 'sold', 'spoke',
  'stood', 'told', 'wrote', 'won', 'put', 'set', 'cut', 'cost', 'hit', 'let',
  'shows', 'show', 'reveals', 'reveal', 'suggests', 'suggest', 'remains'
])

/** Nouns that are already plural, though writers often treat them as singular. */
const PLURAL_NOUNS = Object.freeze([
  'data', 'criteria', 'phenomena', 'media', 'analyses', 'hypotheses',
  'bacteria', 'strata', 'curricula', 'theses', 'indices', 'matrices',
  'alumni', 'foci'
])

/** Singular verb forms and their plural equivalents. */
const AGREEMENT_FIXES = Object.freeze({
  is: 'are', was: 'were', has: 'have', does: 'do', seems: 'seem',
  shows: 'show', suggests: 'suggest', indicates: 'indicate',
  remains: 'remain', appears: 'appear', supports: 'support'
})

/** Words ending in -s that are not plural nouns. */
const SINGULAR_S_WORDS = Object.freeze([
  'series', 'species', 'means', 'news', 'always', 'perhaps', 'whereas',
  'towards', 'besides', 'yes', 'gas', 'lens', 'bias', 'campus', 'census'
])

const MODALS = Object.freeze([
  'can', 'could', 'may', 'might', 'will', 'would', 'shall', 'should', 'must'
])

/** Verbs that commonly follow a bare "this" and leave the referent unnamed. */
const REPORTING_VERBS = Object.freeze([
  'suggests', 'suggest', 'shows', 'show', 'indicates', 'indicate', 'means',
  'mean', 'demonstrates', 'demonstrate', 'implies', 'imply', 'highlights',
  'highlight', 'reveals', 'reveal', 'illustrates', 'illustrate', 'reflects',
  'reflect', 'leads', 'lead', 'results', 'result', 'allows', 'allow',
  'enables', 'enable', 'creates', 'create', 'causes', 'cause', 'explains',
  'explain', 'supports', 'support', 'confirms', 'confirm', 'raises', 'raise',
  'provides', 'provide', 'makes', 'make', 'gives', 'give', 'seems', 'seem',
  'appears', 'appear', 'occurs', 'occur', 'requires', 'require', 'involves',
  'involve', 'includes', 'include', 'points', 'point', 'helps', 'help',
  'tells', 'tell', 'happens', 'happen', 'contributes', 'contribute',
  'presents', 'present', 'offers', 'offer', 'has', 'have', 'had'
])

// ===== phrases.gs =====
/**
 * Fixed phrases that pad academic prose, paired with what usually replaces
 * them. Matched on lowercased word tokens, so punctuation does not interfere.
 */

const BASE_PADDING_PHRASES = Object.freeze([
  { phrase: 'due to', suggestion: 'because of — or name the cause directly' },
  { phrase: 'in order to', suggestion: 'to' },
  { phrase: 'the ability to', suggestion: 'usually deletable: "limits use", not "limits the ability to use"' },
  { phrase: 'has the ability to', suggestion: 'can' },
  { phrase: 'has the potential to', suggestion: 'could, or may' },
  { phrase: 'is able to', suggestion: 'can' },
  { phrase: 'are able to', suggestion: 'can' },
  { phrase: 'the fact that', suggestion: 'that' },
  { phrase: 'in terms of', suggestion: 'usually deletable' },
  { phrase: 'with respect to', suggestion: 'about, or for' },
  { phrase: 'with regard to', suggestion: 'about, or for' },
  { phrase: 'a number of', suggestion: 'several, many — or the actual number' },
  { phrase: 'a majority of', suggestion: 'most' },
  { phrase: 'the presence of', suggestion: 'usually deletable' },
  { phrase: 'it is important to note that', suggestion: 'delete, and state the point' },
  { phrase: 'it should be noted that', suggestion: 'delete, and state the point' },
  { phrase: 'it is worth noting that', suggestion: 'delete, and state the point' },
  { phrase: 'for the purpose of', suggestion: 'to' },
  { phrase: 'in the event that', suggestion: 'if' },
  { phrase: 'prior to', suggestion: 'before' },
  { phrase: 'subsequent to', suggestion: 'after' },
  { phrase: 'at this point in time', suggestion: 'now' },
  { phrase: 'there is', suggestion: 'put the real subject first' },
  { phrase: 'there are', suggestion: 'put the real subject first' },
  { phrase: 'there was', suggestion: 'put the real subject first' },
  { phrase: 'there were', suggestion: 'put the real subject first' }
])

/** Every phrase the wordy-phrase rule matches. */
function paddingPhrases () {
  return BASE_PADDING_PHRASES.concat(REDUNDANT_PAIRS)
}

/** Redundant pairs: one half already means the whole. */
const REDUNDANT_PAIRS = Object.freeze([
  { phrase: 'each and every', suggestion: 'each, or every' },
  { phrase: 'first and foremost', suggestion: 'first' },
  { phrase: 'past history', suggestion: 'history' },
  { phrase: 'future plans', suggestion: 'plans' },
  { phrase: 'end result', suggestion: 'result' },
  { phrase: 'final outcome', suggestion: 'outcome' },
  { phrase: 'final conclusion', suggestion: 'conclusion' },
  { phrase: 'basic fundamentals', suggestion: 'fundamentals' },
  { phrase: 'close proximity', suggestion: 'near' },
  { phrase: 'completely eliminate', suggestion: 'eliminate' },
  { phrase: 'absolutely essential', suggestion: 'essential' },
  { phrase: 'advance planning', suggestion: 'planning' },
  { phrase: 'actual fact', suggestion: 'fact' },
  { phrase: 'added bonus', suggestion: 'bonus' },
  { phrase: 'new innovation', suggestion: 'innovation' },
  { phrase: 'personal opinion', suggestion: 'opinion' },
  { phrase: 'unexpected surprise', suggestion: 'surprise' },
  { phrase: 'brief summary', suggestion: 'summary' },
  { phrase: 'join together', suggestion: 'join' },
  { phrase: 'combine together', suggestion: 'combine' },
  { phrase: 'merge together', suggestion: 'merge' },
  { phrase: 'return back', suggestion: 'return' },
  { phrase: 'revert back', suggestion: 'revert' },
  { phrase: 'repeat again', suggestion: 'repeat' },
  { phrase: 'plan ahead', suggestion: 'plan' }
])

/** Claims with no source attached. */
const AUTHORITY_PHRASES = Object.freeze([
  { phrase: 'studies have shown' }, { phrase: 'studies show' },
  { phrase: 'research has shown' }, { phrase: 'research shows' },
  { phrase: 'research suggests' }, { phrase: 'research indicates' },
  { phrase: 'prior work has shown' }, { phrase: 'the literature suggests' },
  { phrase: 'scholars have argued' }, { phrase: 'researchers have found' },
  { phrase: 'many scholars' }, { phrase: 'many researchers' },
  { phrase: 'some scholars' }, { phrase: 'some researchers' },
  { phrase: 'experts agree' }, { phrase: 'it is widely believed' },
  { phrase: 'it is widely accepted' }, { phrase: 'it is generally accepted' },
  { phrase: 'it is well known' }, { phrase: 'it is often argued' },
  { phrase: 'it has long been' }, { phrase: 'it is commonly assumed' }
])

// ===== verbForms.gs =====
/**
 * Nominalization -> the verb it was built from. Too irregular to derive by
 * stripping suffixes, so this is an explicit map of the forms that actually
 * turn up in academic prose. Absent entries simply get no verb suggestion.
 */

const NOMINALIZATION_VERBS = Object.freeze({
  analysis: 'analyze',
  application: 'apply',
  assessment: 'assess',
  assumption: 'assume',
  classification: 'classify',
  collection: 'collect',
  comparison: 'compare',
  conclusion: 'conclude',
  connection: 'connect',
  consideration: 'consider',
  construction: 'construct',
  contribution: 'contribute',
  correction: 'correct',
  decision: 'decide',
  description: 'describe',
  detection: 'detect',
  determination: 'determine',
  development: 'develop',
  difference: 'differ',
  discussion: 'discuss',
  distribution: 'distribute',
  evaluation: 'evaluate',
  examination: 'examine',
  expansion: 'expand',
  explanation: 'explain',
  exploration: 'explore',
  extension: 'extend',
  identification: 'identify',
  implementation: 'implement',
  improvement: 'improve',
  interpretation: 'interpret',
  introduction: 'introduce',
  investigation: 'investigate',
  judgment: 'judge',
  justification: 'justify',
  measurement: 'measure',
  modification: 'modify',
  observation: 'observe',
  prediction: 'predict',
  presentation: 'present',
  production: 'produce',
  provision: 'provide',
  recommendation: 'recommend',
  reduction: 'reduce',
  reference: 'refer',
  reflection: 'reflect',
  resolution: 'resolve',
  revision: 'revise',
  selection: 'select',
  solution: 'solve',
  statement: 'state',
  suggestion: 'suggest',
  validation: 'validate',
  verification: 'verify'
})

/** Verbs that carry no meaning of their own before a nominalization. */
const LIGHT_VERBS = Object.freeze([
  'perform', 'performs', 'performed', 'performing',
  'conduct', 'conducts', 'conducted', 'conducting',
  'make', 'makes', 'made', 'making',
  'provide', 'provides', 'provided', 'providing',
  'give', 'gives', 'gave', 'giving',
  'carry', 'carries', 'carried', 'carrying',
  'undertake', 'undertakes', 'undertook', 'undertaken', 'undertaking',
  'take', 'takes', 'took', 'taken', 'taking',
  'reach', 'reaches', 'reached', 'reaching',
  'offer', 'offers', 'offered', 'offering',
  'obtain', 'obtains', 'obtained', 'obtaining',
  'achieve', 'achieves', 'achieved', 'achieving',
  'engage', 'engages', 'engaged', 'engaging'
])

/** Particles that sit between a light verb and its object. */
const LIGHT_VERB_PARTICLES = Object.freeze(['out', 'into', 'up', 'in', 'forward'])

// ===== tokenize.gs =====
/**
 * Offset-preserving tokenization. Every token and sentence carries its
 * absolute index into the source string so findings map back to document
 * ranges for Document.setSelection().
 */

const ABBREVIATIONS = Object.freeze([
  'e.g.', 'i.e.', 'et al.', 'cf.', 'vs.', 'etc.', 'Fig.', 'Eq.', 'No.',
  'Dr.', 'Mr.', 'Mrs.', 'Ms.', 'Prof.', 'St.', 'Jr.', 'Sr.', 'approx.'
])

/**
 * Split text into sentences, preserving absolute offsets.
 * @param {string} text
 * @returns {Array<{text: string, start: number, end: number}>}
 */
function splitSentences (text) {
  if (typeof text !== 'string' || text.length === 0) return []

  const boundary = /[.!?]["')\]]?(?=\s)/g
  const sentences = []
  let cursor = 0
  let match

  while ((match = boundary.exec(text)) !== null) {
    const end = match.index + match[0].length
    const candidate = text.slice(cursor, end)
    if (endsWithAbbreviation(candidate)) continue

    sentences.push(makeSentence(text, cursor, end))
    cursor = skipWhitespace(text, end)
    boundary.lastIndex = cursor
  }

  if (cursor < text.length) {
    sentences.push(makeSentence(text, cursor, text.length))
  }
  return sentences.filter(function (s) { return s.text.length > 0 })
}

function makeSentence (text, start, end) {
  const raw = text.slice(start, end)
  const leadingTrim = raw.length - raw.replace(/^\s+/, '').length
  return Object.freeze({
    text: raw.trim(),
    start: start + leadingTrim,
    end: start + leadingTrim + raw.trim().length
  })
}

function endsWithAbbreviation (candidate) {
  const tail = candidate.slice(-10).toLowerCase()
  return ABBREVIATIONS.some(function (abbr) {
    return tail.endsWith(abbr.toLowerCase())
  })
}

function skipWhitespace (text, index) {
  let i = index
  while (i < text.length && /\s/.test(text[i])) i += 1
  return i
}

/**
 * Word tokens within a sentence, with offsets absolute to the source string.
 * @param {{text: string, start: number}} sentence
 * @returns {Array<{word: string, lower: string, start: number, end: number}>}
 */
function tokenizeWords (sentence) {
  const pattern = /[A-Za-z][A-Za-z'’-]*/g
  const tokens = []
  let match
  let previousEnd = 0

  while ((match = pattern.exec(sentence.text)) !== null) {
    const gap = sentence.text.slice(previousEnd, match.index)
    tokens.push(Object.freeze({
      word: match[0],
      lower: match[0].toLowerCase().replace(/’/g, "'"),
      start: sentence.start + match.index,
      end: sentence.start + match.index + match[0].length,
      // Punctuation before this token ends any noun phrase spanning it.
      breaksPhrase: /[^\s]/.test(gap)
    }))
    previousEnd = match.index + match[0].length
  }
  return tokens
}

/**
 * Text between two absolute offsets, relative to a sentence's own start.
 * @param {{text: string, start: number}} sentence
 * @param {number} absoluteStart
 * @param {number} absoluteEnd
 * @returns {string}
 */
function sliceSentence (sentence, absoluteStart, absoluteEnd) {
  return sentence.text.slice(
    absoluteStart - sentence.start,
    absoluteEnd - sentence.start
  )
}

// ===== phraseMatch.gs =====
/**
 * Shared multi-word phrase matching. Used by any rule whose detection is a
 * fixed list of phrases rather than a grammatical pattern.
 */

/**
 * Find every listed phrase in a sentence, longest first so that nested
 * phrases do not both fire.
 * @param {{text: string, start: number}} sentence
 * @param {Array<Object>} tokens
 * @param {Array<{phrase: string}>} entries
 * @returns {Array<{start: number, end: number, phrase: string, entry: Object}>}
 */
function findPhrases (sentence, tokens, entries) {
  const consumed = {}
  const matches = []

  byDescendingLength(entries).forEach(function (entry) {
    const words = entry.phrase.split(' ')
    for (let i = 0; i + words.length <= tokens.length; i += 1) {
      if (!matchesAt(tokens, i, words)) continue
      if (anyConsumed(consumed, i, words.length)) continue

      markConsumed(consumed, i, words.length)
      const first = tokens[i]
      const last = tokens[i + words.length - 1]
      matches.push({
        start: first.start,
        end: last.end,
        phrase: sliceSentence(sentence, first.start, last.end),
        entry: entry
      })
    }
  })

  return matches.sort(function (a, b) { return a.start - b.start })
}

function byDescendingLength (entries) {
  return entries.slice().sort(function (a, b) {
    return b.phrase.split(' ').length - a.phrase.split(' ').length
  })
}

function matchesAt (tokens, index, words) {
  return words.every(function (word, offset) {
    return tokens[index + offset].lower === word
  })
}

function anyConsumed (consumed, index, length) {
  for (let k = index; k < index + length; k += 1) {
    if (consumed[k]) return true
  }
  return false
}

function markConsumed (consumed, index, length) {
  for (let k = index; k < index + length; k += 1) consumed[k] = true
}

// ===== passiveRule.gs =====
/**
 * Rules: passive voice, split by whether the actor is recoverable.
 * One scan finds every "be/get + past participle"; the two rules differ only
 * in which half of that set they report.
 */

const MAX_INTERVENING_TOKENS = 3
const AGENT_SEARCH_WINDOW = 6

const PASSIVE_RULE = Object.freeze({
  id: 'passive-agentless',
  label: 'Passive, no actor',
  analyze: function (sentence, tokens) {
    return findPassives(sentence, tokens)
      .filter(function (hit) { return !hit.hasAgent })
      .map(function (hit) { return toFinding(sentence, hit, agentlessQuestion) })
  }
})

const AGENTED_PASSIVE_RULE = Object.freeze({
  id: 'passive-agented',
  label: 'Passive, actor named',
  analyze: function (sentence, tokens) {
    return findPassives(sentence, tokens)
      .filter(function (hit) { return hit.hasAgent })
      .map(function (hit) { return toFinding(sentence, hit, agentedQuestion) })
  }
})

/** Every passive construction in the sentence, flagged for agent presence. */
function findPassives (sentence, tokens) {
  const hits = []
  let i = 0

  while (i < tokens.length) {
    if (!isAuxiliary(tokens[i].lower)) {
      i += 1
      continue
    }

    const participleIndex = findParticiple(tokens, i + 1)
    if (participleIndex === -1) {
      i += 1
      continue
    }

    hits.push(Object.freeze({
      auxiliary: tokens[i],
      participle: tokens[participleIndex],
      hasAgent: hasNamedAgent(tokens, participleIndex)
    }))
    i = participleIndex + 1
  }
  return hits
}

function isAuxiliary (lower) {
  return BE_FORMS.indexOf(lower) !== -1 || GET_FORMS.indexOf(lower) !== -1
}

/** Index of the participle following `from`, or -1 if the chain breaks. */
function findParticiple (tokens, from) {
  let skipped = 0
  for (let j = from; j < tokens.length; j += 1) {
    const lower = tokens[j].lower
    if (isParticiple(lower)) return j
    if (!isSkippable(lower) || skipped >= MAX_INTERVENING_TOKENS) return -1
    skipped += 1
  }
  return -1
}

function isSkippable (lower) {
  return INTERVENERS.indexOf(lower) !== -1 ||
    BE_FORMS.indexOf(lower) !== -1 ||
    /ly$/.test(lower)
}

function isParticiple (lower) {
  if (NON_PARTICIPLE_ED.indexOf(lower) !== -1) return false
  if (ADJECTIVAL_ED.indexOf(lower) !== -1) return false
  if (IRREGULAR_PARTICIPLES.indexOf(lower) !== -1) return true
  return /ed$/.test(lower) && lower.length >= 4
}

function hasNamedAgent (tokens, participleIndex) {
  const limit = Math.min(tokens.length, participleIndex + 1 + AGENT_SEARCH_WINDOW)
  for (let j = participleIndex + 1; j < limit; j += 1) {
    if (tokens[j].lower === 'by') return true
    if (isAuxiliary(tokens[j].lower)) return false
  }
  return false
}

function toFinding (sentence, hit, buildQuestion) {
  const phrase = sliceSentence(sentence, hit.auxiliary.start, hit.participle.end)
  return {
    start: hit.auxiliary.start,
    end: hit.participle.end,
    phrase: phrase,
    sentence: sentence.text,
    question: buildQuestion(phrase)
  }
}

function agentlessQuestion (phrase) {
  return '“' + phrase + '” — by whom? If the actor matters to your ' +
    'argument, name it. If it genuinely does not, this passive may be right.'
}

function agentedQuestion (phrase) {
  return '“' + phrase + '” — you already know who acted. Could they be the ' +
    'subject instead? Active usually reads better once the actor is named.'
}

// ===== nominalizationRule.gs =====
/**
 * Rule: of-genitive built on a nominalization ("the usage of GAI").
 * Collapsing these to a compound ("GAI usage") shortens the sentence and
 * puts the concrete noun first.
 */

const MAX_OBJECT_TOKENS = 2

const OBJECT_STOPPERS = Object.freeze([
  'in', 'on', 'for', 'with', 'to', 'from', 'at', 'by', 'and', 'or', 'but',
  'that', 'which', 'as', 'than', 'because', 'while', 'when', 'is', 'are',
  'was', 'were', 'has', 'have', 'had', 'of'
])

const NOMINALIZATION_RULE = Object.freeze({
  id: 'nominalization-of',
  label: 'Nominalization',
  analyze: analyzeNominalizations
})

function analyzeNominalizations (sentence, tokens) {
  const findings = []

  for (let i = 0; i < tokens.length - 1; i += 1) {
    if (tokens[i + 1].lower !== 'of') continue
    if (!isNominalization(tokens[i].lower)) continue
    if (isProperNoun(tokens[i], i)) continue
    if (hasGoverningLightVerb(tokens, i)) continue

    findings.push(buildNominalizationFinding(sentence, tokens, i))
  }
  return findings
}

function isNominalization (lower) {
  if (NOMINALIZATION_STOPLIST.indexOf(lower) !== -1) return false
  if (NOMINALIZATION_EXTRAS.indexOf(lower) !== -1) return true
  if (lower.length < 6) return false
  return NOMINALIZATION_SUFFIXES.some(function (suffix) {
    return lower.slice(-suffix.length) === suffix
  })
}

/** Mid-sentence capitals are almost always names, not nominalizations. */
function isProperNoun (token, index) {
  return index > 0 && /^[A-Z]/.test(token.word)
}

function buildNominalizationFinding (sentence, tokens, headIndex) {
  const startToken = precedingDeterminer(tokens, headIndex) || tokens[headIndex]
  const object = collectObject(tokens, headIndex + 1)
  const endToken = object.tokens.length > 0
    ? object.tokens[object.tokens.length - 1]
    : tokens[headIndex + 1]

  const phrase = sliceSentence(sentence, startToken.start, endToken.end)
  const suggestion = object.tokens.length > 0
    ? object.tokens.map(function (t) { return t.word }).join(' ') + ' ' +
      tokens[headIndex].word
    : ''

  return {
    start: startToken.start,
    end: endToken.end,
    phrase: phrase,
    sentence: sentence.text,
    question: nominalizationQuestion(phrase, suggestion)
  }
}

function precedingDeterminer (tokens, headIndex) {
  if (headIndex === 0) return null
  const candidate = tokens[headIndex - 1]
  return DETERMINERS.indexOf(candidate.lower) === -1 ? null : candidate
}

/** The noun phrase after "of", minus its own determiner. */
function collectObject (tokens, ofIndex) {
  const collected = []
  let j = ofIndex + 1

  while (j < tokens.length && DETERMINERS.indexOf(tokens[j].lower) !== -1) j += 1

  while (j < tokens.length && collected.length < MAX_OBJECT_TOKENS) {
    if (tokens[j].breaksPhrase) break
    if (endsNounPhrase(tokens[j].lower)) break
    collected.push(tokens[j])
    j += 1
  }
  return { tokens: collected }
}

/** Nouns rarely end in -ed, so an -ed token is the verb, not the object. */
function endsNounPhrase (lower) {
  return OBJECT_STOPPERS.indexOf(lower) !== -1 ||
    IRREGULAR_PAST.indexOf(lower) !== -1 ||
    /ed$/.test(lower)
}

function nominalizationQuestion (phrase, suggestion) {
  if (suggestion.length === 0) {
    return '“' + phrase + '” — this noun hides a verb. Can the sentence say ' +
      'who does what instead?'
  }
  return '“' + phrase + '” — try “' + suggestion + '”. Nominalizations bury ' +
    'the verb, and of-phrases stack up fast.'
}

// ===== lightVerbRule.gs =====
/**
 * Rule: light verb carrying a nominalization ("performed an analysis").
 * The real verb is trapped inside the noun; freeing it usually removes two
 * or three words. Takes precedence over the of-genitive rule, which skips
 * any nominalization already governed by a light verb.
 */

const MAX_LOOKAHEAD_TOKENS = 3

const LIGHT_VERB_STOPPERS = Object.freeze([
  'of', 'for', 'with', 'to', 'from', 'at', 'by', 'and', 'or', 'that',
  'which', 'is', 'are', 'was', 'were', 'has', 'have', 'had', 'not'
])

const LIGHT_VERB_RULE = Object.freeze({
  id: 'light-verb',
  label: 'Buried verb',
  analyze: analyzeLightVerbs
})

function analyzeLightVerbs (sentence, tokens) {
  const findings = []

  for (let i = 0; i < tokens.length - 1; i += 1) {
    if (LIGHT_VERBS.indexOf(tokens[i].lower) === -1) continue

    const headIndex = findGovernedNominalization(tokens, i)
    if (headIndex === -1) continue

    findings.push(buildLightVerbFinding(sentence, tokens, i, headIndex))
  }
  return findings
}

/** Index of the nominalization this light verb governs, or -1. */
function findGovernedNominalization (tokens, verbIndex) {
  let j = verbIndex + 1
  if (j < tokens.length && LIGHT_VERB_PARTICLES.indexOf(tokens[j].lower) !== -1) {
    j += 1
  }

  let examined = 0
  while (j < tokens.length && examined < MAX_LOOKAHEAD_TOKENS) {
    if (tokens[j].breaksPhrase) return -1
    const lower = tokens[j].lower
    if (LIGHT_VERB_STOPPERS.indexOf(lower) !== -1) return -1
    if (isNominalization(lower) && !isProperNoun(tokens[j], j)) return j
    if (DETERMINERS.indexOf(lower) === -1) examined += 1
    j += 1
  }
  return -1
}

function buildLightVerbFinding (sentence, tokens, verbIndex, headIndex) {
  const phrase = sliceSentence(
    sentence, tokens[verbIndex].start, tokens[headIndex].end
  )
  const verb = NOMINALIZATION_VERBS[tokens[headIndex].lower]

  return {
    start: tokens[verbIndex].start,
    end: tokens[headIndex].end,
    phrase: phrase,
    sentence: sentence.text,
    question: lightVerbQuestion(phrase, verb)
  }
}

function lightVerbQuestion (phrase, verb) {
  if (!verb) {
    return '“' + phrase + '” — the verb is hiding inside the noun. Can it do ' +
      'the work directly?'
  }
  return '“' + phrase + '” — try “' + verb + '”. The real verb is trapped in ' +
    'the noun, and freeing it drops two or three words.'
}

/** True when a light verb governs the nominalization at `headIndex`. */
function hasGoverningLightVerb (tokens, headIndex) {
  const earliest = Math.max(0, headIndex - MAX_LOOKAHEAD_TOKENS - 1)
  for (let j = headIndex - 1; j >= earliest; j -= 1) {
    if (LIGHT_VERBS.indexOf(tokens[j].lower) !== -1) return true
    if (LIGHT_VERB_STOPPERS.indexOf(tokens[j].lower) !== -1) return false
  }
  return false
}

// ===== phraseRule.gs =====
/**
 * Rule: fixed padding phrases with known replacements ("due to", "in order
 * to", "the ability to"), plus redundant pairs ("past history").
 */

const PHRASE_RULE = Object.freeze({
  id: 'padding-phrase',
  label: 'Wordy phrase',
  analyze: analyzePaddingPhrases
})

function analyzePaddingPhrases (sentence, tokens) {
  return findPhrases(sentence, tokens, paddingPhrases()).map(function (match) {
    return {
      start: match.start,
      end: match.end,
      phrase: match.phrase,
      sentence: sentence.text,
      question: '“' + match.phrase + '” — try: ' + match.entry.suggestion + '.'
    }
  })
}

// ===== authorityRule.gs =====
/**
 * Rule: claims attributed to nobody in particular ("studies have shown").
 * Same question the passive rules ask -- who? -- applied to citation rather
 * than to grammar.
 */

const AUTHORITY_RULE = Object.freeze({
  id: 'unattributed-claim',
  label: 'Unattributed claim',
  analyze: analyzeUnattributedClaims
})

function analyzeUnattributedClaims (sentence, tokens) {
  return findPhrases(sentence, tokens, AUTHORITY_PHRASES).map(function (match) {
    return {
      start: match.start,
      end: match.end,
      phrase: match.phrase,
      sentence: sentence.text,
      question: '“' + match.phrase + '” — which ones? A citation or a named ' +
        'author makes the claim checkable; without one it reads as hearsay.'
    }
  })
}

// ===== agreementRule.gs =====
/**
 * Rule: number agreement slips that recur in academic prose --
 * "data is", "this data", "amount of students", "less students".
 */

const AGREEMENT_RULE = Object.freeze({
  id: 'agreement',
  label: 'Agreement',
  analyze: analyzeAgreement
})

function analyzeAgreement (sentence, tokens) {
  const findings = []

  for (let i = 0; i < tokens.length - 1; i += 1) {
    const finding = checkPluralNounVerb(sentence, tokens, i) ||
      checkSingularDeterminer(sentence, tokens, i) ||
      checkAmountOf(sentence, tokens, i) ||
      checkLess(sentence, tokens, i)

    if (finding) findings.push(finding)
  }
  return findings
}

/** "data is" -> "data are" */
function checkPluralNounVerb (sentence, tokens, i) {
  if (PLURAL_NOUNS.indexOf(tokens[i].lower) === -1) return null
  const fix = AGREEMENT_FIXES[tokens[i + 1].lower]
  if (!fix) return null

  return agreementFinding(sentence, tokens[i], tokens[i + 1],
    tokens[i].word + ' ' + fix)
}

/** "this data" -> "these data" */
function checkSingularDeterminer (sentence, tokens, i) {
  const swap = { this: 'these', that: 'those' }[tokens[i].lower]
  if (!swap) return null
  if (PLURAL_NOUNS.indexOf(tokens[i + 1].lower) === -1) return null

  return agreementFinding(sentence, tokens[i], tokens[i + 1],
    swap + ' ' + tokens[i + 1].word)
}

/** "amount of students" -> "number of students" */
function checkAmountOf (sentence, tokens, i) {
  if (tokens[i].lower !== 'amount' || tokens[i + 1].lower !== 'of') return null
  if (!headIsPlural(tokens, i + 2)) return null

  return agreementFinding(sentence, tokens[i], tokens[i + 1], 'number of')
}

/** "less students" -> "fewer students" */
function checkLess (sentence, tokens, i) {
  if (tokens[i].lower !== 'less') return null
  if (!headIsPlural(tokens, i + 1)) return null

  return agreementFinding(sentence, tokens[i], tokens[i], 'fewer')
}

/** The first non-determiner token from `from`, tested for plurality. */
function headIsPlural (tokens, from) {
  let j = from
  while (j < tokens.length && DETERMINERS.indexOf(tokens[j].lower) !== -1) j += 1
  return j < tokens.length && isPluralNoun(tokens[j].lower)
}

/**
 * Plural test by suffix. The exclusions carry the weight: -ss (process),
 * -ous (various), -is (analysis), -us (status) and -ics (statistics) all end
 * in s without being plural.
 */
function isPluralNoun (lower) {
  if (lower.length < 4) return false
  if (lower.slice(-1) !== 's') return false
  if (SINGULAR_S_WORDS.indexOf(lower) !== -1) return false
  if (DETERMINERS.indexOf(lower) !== -1) return false
  return !/(ss|ous|is|us|ics)$/.test(lower)
}

function agreementFinding (sentence, first, last, suggestion) {
  const phrase = sliceSentence(sentence, first.start, last.end)
  return {
    start: first.start,
    end: last.end,
    phrase: phrase,
    sentence: sentence.text,
    question: '“' + phrase + '” — try “' + suggestion + '”.'
  }
}

// ===== referenceRule.gs =====
/**
 * Rule: a sentence opening with a bare "this" and going straight into a verb.
 * The reader has to guess which idea from the previous sentence is meant, and
 * often several would fit.
 */

const REFERENCE_RULE = Object.freeze({
  id: 'unclear-reference',
  label: 'Unclear reference',
  analyze: analyzeUnclearReferences
})

const BARE_DEMONSTRATIVES = Object.freeze(['this', 'these', 'that', 'those'])

function analyzeUnclearReferences (sentence, tokens) {
  if (tokens.length < 2) return []
  if (BARE_DEMONSTRATIVES.indexOf(tokens[0].lower) === -1) return []
  if (isDiscourseMarker(tokens)) return []
  if (!startsVerbPhrase(tokens[1].lower)) return []

  const phrase = sliceSentence(sentence, tokens[0].start, tokens[1].end)
  return [{
    start: tokens[0].start,
    end: tokens[1].end,
    phrase: phrase,
    sentence: sentence.text,
    question: '“' + phrase + '” — this what? Naming the noun (“this pattern”, ' +
      '“this discrepancy”) tells the reader which idea you mean. Several ' +
      'usually fit.'
  }]
}

/** "That is, ..." is a connective, not a dangling reference. */
function isDiscourseMarker (tokens) {
  return tokens[0].lower === 'that' && tokens[1].lower === 'is'
}

function startsVerbPhrase (lower) {
  return BE_FORMS.indexOf(lower) !== -1 ||
    MODALS.indexOf(lower) !== -1 ||
    REPORTING_VERBS.indexOf(lower) !== -1
}

// ===== inflatedRule.gs =====
/**
 * Rule: single words that are longer than the idea requires.
 */

const INFLATED_WORDS = Object.freeze({
  utilize: 'use', utilizes: 'uses', utilized: 'used', utilizing: 'using',
  utilization: 'use',
  commence: 'begin', commences: 'begins', commenced: 'began',
  endeavor: 'try', endeavour: 'try',
  facilitate: 'help', facilitates: 'helps', facilitated: 'helped',
  ascertain: 'determine', ascertained: 'determined',
  methodology: 'method', methodologies: 'methods',
  individuals: 'people', individual: 'person',
  numerous: 'many', additionally: 'also', approximately: 'about',
  subsequent: 'later', initiate: 'start', initiated: 'started',
  terminate: 'end', terminated: 'ended',
  demonstrate: 'show', demonstrates: 'shows', demonstrated: 'showed',
  necessitate: 'require', necessitates: 'requires',
  aforementioned: 'these, or name them', heretofore: 'until now',
  cognizant: 'aware', requisite: 'required', myriad: 'many',
  plethora: 'many', paradigm: 'model', leverage: 'use'
})

const INFLATED_RULE = Object.freeze({
  id: 'inflated-word',
  label: 'Inflated word',
  analyze: analyzeInflatedWords
})

function analyzeInflatedWords (sentence, tokens) {
  return tokens
    .filter(function (token) {
      return Object.prototype.hasOwnProperty.call(INFLATED_WORDS, token.lower)
    })
    .map(function (token) {
      return {
        start: token.start,
        end: token.end,
        phrase: token.word,
        sentence: sentence.text,
        question: '“' + token.word + '” — try “' +
          INFLATED_WORDS[token.lower] + '”.'
      }
    })
}

// ===== rules.gs =====
/**
 * Rule registry. Adding a pattern means appending to registeredRules() --
 * nothing else changes.
 */

/**
 * Resolved at call time, not load time: Apps Script concatenates .gs files in
 * an unspecified order and top-level const bindings are not hoisted.
 */
function registeredRules () {
  return [
    PASSIVE_RULE,
    AGENTED_PASSIVE_RULE,
    LIGHT_VERB_RULE,
    NOMINALIZATION_RULE,
    AUTHORITY_RULE,
    REFERENCE_RULE,
    AGREEMENT_RULE,
    INFLATED_RULE,
    PHRASE_RULE
  ]
}

/**
 * Run every registered rule over a block of text.
 * @param {string} text
 * @param {number} baseOffset absolute offset of `text` within the document
 * @returns {Array<Object>} findings, ordered by position, no nested overlaps
 */
function analyzeText (text, baseOffset) {
  const offset = baseOffset || 0
  const sentences = splitSentences(text)

  const findings = sentences.reduce(function (accumulated, sentence) {
    return accumulated.concat(analyzeSentence(sentence))
  }, [])

  return dropContained(findings)
    .map(function (finding) {
      return Object.freeze(Object.assign({}, finding, {
        start: finding.start + offset,
        end: finding.end + offset
      }))
    })
    .sort(function (a, b) { return a.start - b.start })
}

function analyzeSentence (sentence) {
  const tokens = tokenizeWords(sentence)

  return registeredRules().reduce(function (accumulated, rule) {
    return accumulated.concat(runRule(rule, sentence, tokens))
  }, [])
}

function runRule (rule, sentence, tokens) {
  try {
    return (rule.analyze(sentence, tokens) || []).map(function (finding) {
      return Object.assign({}, finding, {
        ruleId: rule.id,
        ruleLabel: rule.label
      })
    })
  } catch (error) {
    throw new Error(
      'Rule "' + rule.id + '" failed on sentence "' +
      sentence.text.slice(0, 60) + '": ' + error.message
    )
  }
}

/**
 * Two rules can cover the same words ("the presence of" is both a padding
 * phrase and a nominalization). Keep the widest span, and one per span.
 */
function dropContained (findings) {
  return findings.filter(function (candidate, index) {
    return !findings.some(function (other, otherIndex) {
      if (index === otherIndex) return false
      const contains = other.start <= candidate.start && other.end >= candidate.end
      const identical = other.start === candidate.start && other.end === candidate.end
      return contains && (!identical || otherIndex < index)
    })
  })
}

// ===== Code.gs =====
/**
 * Passive Voice Lens -- entry points and the bridge between rule findings
 * and Google Docs text ranges.
 */

const SIDEBAR_TITLE = 'Passive Voice Lens'
const SCANNABLE_TYPES = ['PARAGRAPH', 'LIST_ITEM']

/**
 * Top-level menu. When published as a real add-on, swap createMenu(...) for
 * createAddonMenu() so the entry nests under Extensions instead.
 */
function onOpen () {
  DocumentApp.getUi()
    .createMenu(SIDEBAR_TITLE)
    .addItem('Show sidebar', 'showSidebar')
    .addToUi()
}

function onInstall () {
  onOpen()
}

function showSidebar () {
  try {
    const html = HtmlService.createHtmlOutputFromFile('Sidebar')
      .setTitle(SIDEBAR_TITLE)
    DocumentApp.getUi().showSidebar(html)
  } catch (error) {
    throw new Error('Could not open the sidebar: ' + error.message)
  }
}

/**
 * Analyze every paragraph in the open document.
 * Offsets stay paragraph-relative because Docs ranges are built per element.
 * @returns {{findings: Array<Object>, wordCount: number, density: string}}
 */
function scanDocument () {
  try {
    const body = DocumentApp.getActiveDocument().getBody()
    const total = body.getNumChildren()
    const collected = []
    let wordCount = 0

    for (let index = 0; index < total; index += 1) {
      const child = body.getChild(index)
      if (SCANNABLE_TYPES.indexOf(child.getType().toString()) === -1) continue

      const text = child.asText().getText()
      if (text.trim().length === 0) continue

      wordCount += countWords(text)
      analyzeText(text, 0).forEach(function (finding) {
        collected.push(withLocation(finding, index))
      })
    }

    return {
      findings: collected,
      wordCount: wordCount,
      density: densityPerHundred(collected.length, wordCount)
    }
  } catch (error) {
    throw new Error('Could not scan this document: ' + error.message)
  }
}

/**
 * Select a finding's text in the document so the writer sees it in context.
 * @param {number} childIndex body child index the finding came from
 * @param {number} start paragraph-relative start offset
 * @param {number} end paragraph-relative end offset, exclusive
 */
function selectFinding (childIndex, start, end) {
  try {
    const doc = DocumentApp.getActiveDocument()
    const element = doc.getBody().getChild(childIndex).asText()
    const range = doc.newRange()
      .addElement(element, start, end - 1)
      .build()
    doc.setSelection(range)
  } catch (error) {
    throw new Error('Could not jump to that sentence: ' + error.message)
  }
}

function withLocation (finding, childIndex) {
  return Object.assign({}, finding, { childIndex: childIndex })
}

function countWords (text) {
  const trimmed = text.trim()
  return trimmed.length === 0 ? 0 : trimmed.split(/\s+/).length
}

function densityPerHundred (count, wordCount) {
  if (wordCount === 0) return '0.0'
  return (count / wordCount * 100).toFixed(1)
}

/**
 * Web app entry point. Lets students check a draft without installing
 * anything, which matters when Cloud projects are restricted and no add-on
 * can be published.
 */
function doGet () {
  return HtmlService.createHtmlOutputFromFile('WebApp')
    .setTitle(SIDEBAR_TITLE)
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
}

/**
 * Analyze pasted text. Nothing is stored or logged by this function.
 * @param {string} text
 * @returns {{findings: Array<Object>, wordCount: number, density: string}}
 */
function analyzeDraft (text) {
  try {
    if (typeof text !== 'string' || text.trim().length === 0) {
      return { findings: [], wordCount: 0, density: '0.0' }
    }
    const findings = analyzeText(text, 0)
    const wordCount = countWords(text)
    return {
      findings: findings,
      wordCount: wordCount,
      density: densityPerHundred(findings.length, wordCount)
    }
  } catch (error) {
    throw new Error('Could not analyze that text: ' + error.message)
  }
}
